import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Layout } from 'antd';
import React from 'react';
import Navbar from '../component/common/Navbar';
import FooterMain from '../component/common/FooterMain';
import { useEffect, memo } from 'react';

const { Header, Footer, Sider, Content } = Layout;

function Main({ children }) {
  
  return (
    <div>
        <Head>
            <title>Read book</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
          <Header className={styles.header_home}>
            <Navbar />
          </Header>
              <Layout className='layout__main'>
                <main style={{overflow: 'hidden'}}>{children}</main>
              </Layout>
          <Footer>
            <FooterMain />
          </Footer>
        </Layout>

        <style jsx global>{`
            .layout__main{
                background:#fff
            }
        `}</style>
    </div>
   
  )
}
export default memo(Main)